#!/bin/bash

# fetching MakeMKV beta key
KEY=$(curl --silent 'https://forum.makemkv.com/forum/viewtopic.php?f=5&t=1053' | grep -oP 'T-[\w\d@]{66}')

# move settings.conf, if found
mkdir -p /root/.MakeMKV
if [[ -f  /config/settings.conf ]]; then
 echo "Found settings.conf. Replacing beta key file."
 cp -f  /config/settings.conf /root/.MakeMKV/
elif ! [ "$KEY" = '' ]; then
 echo "Using MakeMKV beta key: $KEY"
 echo app_Key = "\"$KEY"\" > /root/.MakeMKV/settings.conf
fi